---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ansible_distribution_release}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    
- name: install packages
  package: name={{item}} state=present
  with_items: "{{sshd_packages}}"
