---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: install sshd package(s)
  become: '{{ sshd_privilege_escalation | default(True) }}'
  become_user: root
  with_items: '{{ sshd_packages }}'
  package:
    name: '{{ item }}'
    state: present

- name: templatize sshd_config
  when: sshd_config is defined and sshd_privilege_escalation | bool
  become: yes
  become_user: root
  with_items:
  - f: sshd_config
    d: /etc/ssh
    m: 0644
  notify: sshd_restart
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'

- name: start/enable sshd
  when: sshd_service_managed
  service:
    name: '{{ sshd_service_id }}'
    state: '{{ sshd_service_state }}'
    enabled: '{{ sshd_service_enabled }}'
